# Generated by Django 5.0.7 on 2024-07-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_rename_url_product_path_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'PriceHistory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='path_segment',
            new_name='resource_path',
        ),
        migrations.RemoveField(
            model_name='site',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
